# Generated by Django 5.2.12 on 2026-03-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_is_active_organization_slug_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
