# Generated by Django 5.2.12 on 2026-03-13 00:00

import uuid

from django.db import migrations, models
import django.db.models.deletion
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")], default="member", max_length=20
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=organizations.models._generate_invite_token,
                        editable=False,
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(default=organizations.models._default_invite_expires_at)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to="organizations.user",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to="organizations.user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization", "email"], name="organizatio_organi_85cc5b_idx"),
                    models.Index(fields=["token"], name="organizatio_token_3a0e1d_idx"),
                    models.Index(fields=["status"], name="organizatio_status_37eb60_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="organizationinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("organization", "email"),
                name="uniq_pending_invite_org_email",
            ),
        ),
    ]
