# Generated by Django 6.0.3 on 2026-03-11 05:28

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentchunk_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding_id',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
